language: erlang

otp_release:
  - 17.0
  - 17.1

env:
  - ELIXIR_VSN=1.0.0

before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VSN/Precompiled.zip
  - unzip -qq Precompiled.zip -d elixir

before_script:
  - export PATH=$PWD/elixir/bin:$PATH

script: mix test --trace --no-start
